### ISSUE TITLE
Decoding access_token fails

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [keycloak-client/keycloak-client#73]
When using keycloak-client v3.1.0 with FastAPI (Starlette) trying to decode the `access_token` throws an `AttributeError`.

Starlette Callback class in middleware (taken from `keycloak/extensions/starlette.py` and modified):
```python
[...]
class Callback(EndpointHandler):
    async def get(self, request: Request) -> Response:

        # validate state
        state = request.query_params["state"]
        _state = request.session.pop("state", "unknown")
        if state != _state:
            return PlainTextResponse("Invalid state", status_code=403)

        # retrieve tokens
        code = request.query_params["code"]
        tokens = await self.kc.callback(code)

        # starlette sessions do not have the capacity to store the entire tokens
        # so storing only access token and refresh token
        _tokens = {
            "access_token": tokens["access_token"],
            "refresh_token": tokens["refresh_token"],
        }
        request.session["tokens"] = json.dumps(_tokens)

        # retrieve user info
        access_token = tokens["access_token"]
        user = await self.kc.fetch_userinfo(access_token)
        request.session["user"] = json.dumps(user)

        access_token_data = await self.kc.decode(access_token)
        print(access_token_data)

        return RedirectResponse(self.redirect_uri)
[...]
```

Stacktrace:
```
Traceback (most recent call last):
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 77, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/b1nny/projects/keycloak_demo/./middleware.py", line 110, in __call__
    await Callback(
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/starlette/endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "/home/b1nny/projects/keycloak_demo/./middleware.py", line 72, in get
    access_token_data = await self.kc.decode(access_token)
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/keycloak/core/asynchronous/token.py", line 173, in decode
    await self.jwks,  # type: ignore
  File "/usr/lib/python3.10/asyncio/coroutines.py", line 127, in coro
    res = yield from res
  File "/home/b1nny/virtualenvs/keycloak_demo/lib/python3.10/site-packages/keycloak/core/asynchronous/token.py", line 153, in jwks
    response = await client.get(self.openid.jwks_uri)
AttributeError: 'NoneType' object has no attribute 'jwks_uri'
```

The cause of this seems to be that in `keycloak/core/asynchronous/token.py` on line 153 the `jwks_uri` is obtained from `self.config`, while this should (?) be `config.openid` (like in the `decode()` method below it, for `issuer`). The patch that fixes it for me is as follows:

```patch
153c153
<             response = await client.get(self.openid.jwks_uri)
---
>             response = await client.get(config.openid.jwks_uri)
177d176
< 
```

I am not 100% sure if this is the correct way to achieve my goal, which is to get the roles that are defined in Keycloak.

P.S. `keycloak/core/token.py` contains the same line trying to access `self.openid` on line 139. I have not tested the Flask implementation, so I'm not sure if that is also affected, but it may be.

**Comment by akhilputhiry** [comment]
@ybinnenwegin2ip You are correct. Would you be interested in raising a PR for the same. Thanks.

**Comment by ybinnenwegin2ip** [comment]
> @ybinnenwegin2ip You are correct. Would you be interested in raising a PR for the same. Thanks.

PR opened here! https://github.com/keycloak-client/keycloak-client/pull/74

**Comment by akhilputhiry** [comment]
Thank you @ybinnenwegin2ip
